// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDja6T9EfyzIxg4fQmj2D1M6azwAKgTDwI ',
    appId: '1:762352208381:web:3a8417ff316580e1daf194',
    messagingSenderId: '762352208381',
    projectId: 'bhive-aaaed',
    authDomain: 'bhive-aaaed.firebaseapp.com',
    databaseURL:
        'https://bhive-aaaed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhive-aaaed.appspot.com',
    measurementId: 'G-SJ21VXM1NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSuLHqKgkvZV8uSZZ5C8FRsSYrj1y4qvA',
    appId: '1:762352208381:android:7e920c61eac78781daf194',
    messagingSenderId: '762352208381',
    projectId: 'bhive-aaaed',
    databaseURL:
        'https://bhive-aaaed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhive-aaaed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEG8jcRrmG3tFzePjDpMm2doL5kfyALHE',
    appId: '1:762352208381:ios:950dd22a7484e5c7daf194',
    messagingSenderId: '762352208381',
    projectId: 'bhive-aaaed',
    databaseURL:
        'https://bhive-aaaed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bhive-aaaed.appspot.com',
    iosClientId:
        '762352208381-78gl4jamlrh55vrsj6v2emorrg0kj50u.apps.googleusercontent.com',
    iosBundleId: 'ios',
  );
}
